pages:
  stage: deploy
  image: python:3.11
  tags:
    - docker
  script:
    - pip install mkdocs-material
    - mkdocs build --site-dir public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/
  artifacts:
    paths:
      - public
  only:
    - master
