pages:
  stage: deploy
  image: python:latest
  script:
    - call C:\Users\reis7\anaconda3\Scripts\activate.bat base
    - pip install mkdocs-material
    - mkdocs build --site-dir public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/
  artifacts:
    paths:
      - public
  only:
    - main
